import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
  style: "normal",
  variable: "--font-inter",
  display: "swap",
});

const cal = localFont({
  src: "./fonts/Cal/CalSans-SemiBold.woff2",
  weight: "400",
  style: "normal",
  variable: "--font-cal",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${cal.variable}`}>
      <body>{children}</body>
    </html>
  );
}
